---
version: '2'
services:
  cassandra:
    image: cassandra:3.11.3
    container_name: cassandra
    network_mode: host
    volumes:
      - ${PWD}/data/cassandra:/var/lib/cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_LISTEN_ADDRESS: 199.60.17.212
      CASSANDRA_BROADCAST_ADDRESS: 199.60.17.212
      CASSANDRA_RPC_ADDRESS: 199.60.17.212

